version: "3.7"

services:
    app:
        container_name: meditation-web-app 
        restart: always
        build: .
        ports:
            - "3000:3000"
        volumes:
            - ./:/usr/src/backendapiman
        links:
            - mongo
    mongo:
        container_name: mongo-meditation
        image: mongo
        ports: 
            - "27017:27017"
