version: '3.6'
services:
    bastos-backend-node: 
        container_name: bastos-node
        image: node:8.11.1
        build: ./
        command: npm start
        working_dir: /usr/src/bastosBackEnd
        ports: 
            - "5000:5000"
        depends_on:
                - mongo-bastos
    mongo-bastos:
        image: mongo
        ports: 
            - "27017:27017"